apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom-hosts
  namespace: kube-system
  labels:
    managed-by: argocd
    app: coredns-custom-hosts
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  Corefile: |
    .:53 {
        errors
        health
        hosts {
            192.168.3.51 golden-i.cluster
            fallthrough
        }
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    } 