apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: knative-catchall
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
    - match: HostRegexp(`[a-z0-9-]+\.[a-z0-9-]+\.scudco\.com`)
      kind: Rule
      services:
        - name: kourier
          namespace: kourier-system
          port: 80
