apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: contour
    targetRevision: 17.0.2 # Use latest stable or update as needed
    helm:
      values: |
        # Contour Helm values for k3s + MetalLB + Gateway API
        # See https://github.com/bitnami/charts/tree/main/bitnami/contour for all options
        gatewayController:
          enabled: true
        envoy:
          image:
            registry: docker.io
            repository: bitnami/envoy
            tag: 1.34.1-debian-12-r3 
          service:
            type: LoadBalancer
            loadBalancerIP: 192.168.1.100  # Set to an IP from your MetalLB pool
          replicaCount: 1
        contour:
          replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: projectcontour
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 