apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns-custom-hosts
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/bdkech/cluster-config.git
    targetRevision: main
    path: manifests/coredns/overlays/custom-hosts
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 