apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-serving
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/bdkech/cluster-config.git
    targetRevision: main
    path: manifests/knative
  destination:
    server: https://kubernetes.default.svc
    namespace: knative-serving
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  dependsOn:
    - cluster-namespaces
    - knative-operator