apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/knative/operator
    targetRevision: knative-v1.15.0 # Use latest stable version
    path: config
  destination:
    server: https://kubernetes.default.svc
    namespace: knative-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  dependsOn:
    - cluster-namespaces