apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway-fabric-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nginxinc/nginx-gateway-fabric.git
    targetRevision: v1.5.1
    path: deploy/crds
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 