apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway-fabric
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx-gateway-fabric
    targetRevision: 2.0.2 # Use latest stable or update as needed
    helm:
      values: |
        # NGINX Gateway Fabric custom values
        # See https://github.com/nginxinc/nginx-gateway-fabric/tree/main/charts/nginx-gateway-fabric for all options
        replicaCount: 1
        # Add more customizations below as needed
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  dependsOn:
    - nginx-gateway-fabric-crds 