apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 35.2.0 # Use latest stable or update as needed
    helm:
      values: |
        ingressRoute:
          dashboard:
            enabled: true
            matchRule: Host(`dashboard.localhost`)
            entryPoints:
              - web
        providers:
          kubernetesGateway:
            enabled: true
        gateway:
          namespacePolicy: All
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  dependsOn:
    - gateway-api-crds
    - metallb 