apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    # PATCH: Add hosts block for golden-i.cluster
    hosts {
      192.168.3.51 golden-i.cluster
      fallthrough
    } 